import '@polymer/iron-dropdown';
import '@polymer/iron-icons';
import '@polymer/iron-input';
import '@polymer/iron-label';
import '@polymer/paper-button';
import '@polymer/paper-card';
import '@polymer/paper-checkbox';
import '@polymer/paper-dialog';
import '@polymer/paper-slider';
import '@polymer/iron-ajax';
import '@polymer/iron-icon';
import '@polymer/iron-iconset-svg';
import '@polymer/iron-list';
import '@polymer/iron-media-query';
import '@polymer/paper-toast';
import '@polymer/app-layout';
import '@polymer/paper-input/paper-input';
import '@polymer/iron-overlay-behavior/iron-overlay-backdrop'