import './iron-dropdown/iron-dropdown.js';
import './iron-icons/iron-icons.js';
import './iron-input/iron-input.js';
import './iron-label/iron-label.js';
import './paper-button/paper-button.js';
import './paper-card/paper-card.js';
import './paper-checkbox/paper-checkbox.js';
import './paper-dialog/paper-dialog.js';
import './iron-ajax/iron-ajax.js';
import './iron-icon/iron-icon.js';
import './iron-iconset-svg/iron-iconset-svg.js';
import './iron-list/iron-list.js';
import './iron-media-query/iron-media-query.js';
import './paper-toast/paper-toast.js';
import './app-layout/app-layout.js';
import './paper-input/paper-input.js';
import './iron-overlay-behavior/iron-overlay-backdrop.js';

import { IronA11yAnnouncer } from './iron-a11y-announcer/iron-a11y-announcer.js';
import { IronA11yKeysBehavior } from './iron-a11y-keys-behavior/iron-a11y-keys-behavior.js';
import { IronResizableBehavior } from './iron-resizable-behavior/iron-resizable-behavior.js';
import { IronScrollTargetBehavior } from './iron-scroll-target-behavior/iron-scroll-target-behavior.js';

export {IronA11yAnnouncer, IronA11yKeysBehavior, IronResizableBehavior,IronScrollTargetBehavior};


// import { AppLayoutBehavior } from '../app-layout-behavior/app-layout-behavior.js';
// import { AppScrollEffectsBehavior } from '../app-scroll-effects/app-scroll-effects-behavior.js';
// import { Base } from "@polymer/polymer/polymer-legacy.js";
// import { Debouncer } from "@polymer/polymer/lib/utils/debounce.js";
// import { DisableUpgradeMixin } from '@polymer/polymer/lib/mixins/disable-upgrade-mixin.js';
// import { DomModule } from '@polymer/polymer/lib/elements/dom-module.js';
// import { FlattenedNodesObserver } from '@polymer/polymer/lib/utils/flattened-nodes-observer.js';
// import { GestureEventListeners } from '@polymer/polymer/lib/mixins/gesture-event-listeners.js';
// import { IronA11yAnnouncer } from './iron-a11y-announcer/iron-a11y-announcer.js';
// import { IronA11yKeysBehavior } from './iron-a11y-keys-behavior/iron-a11y-keys-behavior.js';
// import { IronButtonState, IronButtonStateImpl } from "../iron-behaviors/iron-button-state.js";
// import { IronCheckedElementBehavior, IronCheckedElementBehaviorImpl } from "../iron-checked-element-behavior/iron-checked-element-behavior.js";
// import { IronControlState } from "../iron-behaviors/iron-control-state.js";
// import { IronFitBehavior } from "../iron-fit-behavior/iron-fit-behavior.js";
// import { IronFocusablesHelper } from './iron-focusables-helper.js';
// import { IronFormElementBehavior } from "../iron-form-element-behavior/iron-form-element-behavior.js";
// import { IronMeta } from "../iron-meta/iron-meta.js";
// import { IronOverlayBehavior, IronOverlayBehaviorImpl } from "../iron-overlay-behavior/iron-overlay-behavior.js";
// import { IronOverlayManager } from './iron-overlay-manager.js';
// import { IronResizableBehavior } from "../../iron-resizable-behavior/iron-resizable-behavior.js";
// import { IronScrollTargetBehavior } from './iron-scroll-target-behavior/iron-scroll-target-behavior.js';
// import { IronValidatableBehavior } from "../iron-validatable-behavior/iron-validatable-behavior.js";
// import { NeonAnimatableBehavior } from './neon-animatable-behavior.js';
// import { NeonAnimationRunnerBehavior } from "../neon-animation/neon-animation-runner-behavior.js";
// import { OptionalMutableDataBehavior } from "@polymer/polymer/lib/legacy/mutable-data-behavior.js";
// import { PaperButtonBehavior, PaperButtonBehaviorImpl } from "../paper-behaviors/paper-button-behavior.js";
// import { PaperCheckedElementBehavior } from "../paper-behaviors/paper-checked-element-behavior.js";
// import { PaperDialogBehavior } from "../paper-dialog-behavior/paper-dialog-behavior.js";
// import { PaperInkyFocusBehavior } from './paper-inky-focus-behavior.js';
// import { PaperInkyFocusBehaviorImpl } from "../paper-behaviors/paper-inky-focus-behavior.js";
// import { PaperInputAddonBehavior } from './paper-input-addon-behavior.js';
// import { PaperInputBehavior } from './paper-input-behavior.js';
// import { PaperRippleBehavior } from './paper-ripple-behavior.js';
// import { Polymer } from "@polymer/polymer/lib/legacy/polymer-fn.js";
// import { PolymerElement } from '@polymer/polymer/polymer-element.js';
// import { TemplateInstanceBase } from "@polymer/polymer/lib/utils/templatize.js";
// import { Templatizer } from "@polymer/polymer/lib/legacy/templatizer-behavior.js";
// import { _scrollEffects } from '../helpers/helpers.js';
// import { addListener, register, prevent, gestures, removeListener, setTouchAction, resetMouseCanceller } from '@polymer/polymer/lib/utils/gestures.js';
// import { afterNextRender, beforeNextRender } from '@polymer/polymer/lib/utils/render-status.js';
// import { animationFrame, idlePeriod, microTask } from "@polymer/polymer/lib/utils/async.js";
// import { dashToCamelCase } from '@polymer/polymer/lib/utils/case-map.js';
// import { dom } from "@polymer/polymer/lib/legacy/polymer.dom.js";
// import { enqueueDebouncer, flush } from '@polymer/polymer/lib/utils/flush.js';
// import { flush as flush$1, dom } from '@polymer/polymer/lib/legacy/polymer.dom.js';
// import { html } from '@polymer/polymer/lib/utils/html-tag.js';
// import { idlePeriod, timeOut, animationFrame, microTask } from '@polymer/polymer/lib/utils/async.js';
// import { matches, translate } from "@polymer/polymer/lib/utils/path.js";
// import { mixinBehaviors, Class } from '@polymer/polymer/lib/legacy/class.js';
// import { pushScrollLock, removeScrollLock } from './iron-scroll-manager.js';
// import { resolveUrl } from "@polymer/polymer/lib/utils/resolve-url.js";
// import { templatize } from '@polymer/polymer/lib/utils/templatize.js';
// import { useShadow } from '@polymer/polymer/lib/utils/settings.js';
//
//
// export {IronA11yAnnouncer, IronA11yKeysBehavior, IronResizableBehavior,IronScrollTargetBehavior, IronOverlayBehavior, IronOverlayBehaviorImpl};
